### ISSUE TITLE
Add printer based on hostname with https

### ISSUE THREAD

**Issue by svh1985** [2ndalpha/octoremote#1]
Hi,

I downloaded the app, soon realising that the is not suitable for my setup.

So here goes my feature request to get things working:
Is it possible to get support for hostnames when configuring the connection?
It would also be nice to have SSL support, with the option to allow self signed certificates.

Thanks!

**Comment by cyberhomie** [comment]
I agree.

**Comment by mmakris** [comment]
How do I generate an API key?

**Comment by 2ndalpha** [comment]
Sorry it has taken so long time. HTTPS support is in latest version, v 1.24
