### ISSUE TITLE
App can not be installed (iOS v1.28)

### ISSUE THREAD

**Issue by nicolinux** [2ndalpha/octoremote#10]
The latest update seems to miss something. When I try to update, I see the icon filling up (the default iOS installation animation) and then I get an AlertView telling me that the app can't be installed. Looking at the device console I see the following (iOS 9.3.5, iPhone 6):

`
<Error>: *************************************************************
<Error>: **** This application is missing the initialODRSize key. ****
<Error>: ****        This application WILL NOT be imported.       ****
<Error>: ****   Prefetch and initial assets will NOT be fetched.  ****
<Error>: *************************************************************
`

And further down:
`<Error>: 0x16e087000 -[MIPluginKitPluginBundle overlaidInfoPlistWithError:]: 159: Appex bundle at /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Y9tmZF/extracted/Payload/Octo.app/PlugIns/Octo Notifications.appex with id ee.clockwise.octoapp.notification specifies a value (com.apple.usernotifications.service) for the NSExtensionPointIdentifier key in the NSExtension dictionary in its Info.plist that does not correspond to a known extension point.`

**Comment by 2ndalpha** [comment]
Thanks for reporting it. I will let you know when the fix is in App Store.

**Comment by 2ndalpha** [comment]
Fixed in 1.30
