### ISSUE TITLE
Incorrect API Key

### ISSUE THREAD

**Issue by BryanArnold** [2ndalpha/octoremote#13]
I set a new API key for the user, copied and pasted it into the api key section to generate a new QR code, and when I scan it, the software on the phone says incorrect API key.

I do have a username and password set on the interface to access OctoPrint.

I am using haproxy with a HTTP basic authentication, is that compatable with the phone software?

**Comment by 2ndalpha** [comment]
Currently Octo Remote does not support Basic Auth, when you remove it from haproxy you will be able to connect to your printer

**Comment by BryanArnold** [comment]
Thanks for the reply. I'll try that.

**Comment by BryanArnold** [comment]
That worked. Connected great. Thanks.
