### ISSUE TITLE
Custom Commands - Feature Request

### ISSUE THREAD

**Issue by twoolums** [2ndalpha/octoremote#15]
Would love the ability to see being able to run custom commands currently setup in Ocoprint.  Currently I have two entries on my system menu to turn my lights on/off connected to my printer to see my print in the dark.    Being able to toggle this in Octoremote would be awesome.

Thanks
![capture](https://cloud.githubusercontent.com/assets/7130783/23828066/ad045b10-068a-11e7-9586-9c0f6a6a9beb.PNG)

**Comment by 2ndalpha** [comment]
How did you add custom commands? With a plugin?

**Comment by twoolums** [comment]
You add them by editing the config.yaml file.  Here is the octoprint wiki talking about it.

https://github.com/foosel/OctoPrint/wiki/Cookbook:-System-Commands

Another talking about controlling a relay (this is how I control my lights)
https://github.com/foosel/OctoPrint/wiki/Controlling-a-relay-board-from-your-RPi

**Comment by 2ndalpha** [comment]
Implemented in the latest version
