### ISSUE TITLE
Open up octoremote development?

### ISSUE THREAD

**Issue by pelted** [2ndalpha/octoremote#16]
So the Android folks have a pretty decent Octoprint client. Any chance of opening up the development on Octoremtoe so we can get some more of us on this project. I've poked around at starting from scratch, but what you've done so far works well. There are a lot of features that would be great to have and maybe more people helping on the iOS client could work.

**Comment by Patrik-svobodik** [comment]
I would like it too, I do some app modifications and i would like to see this app as open source/development

**Comment by 2ndalpha** [comment]
I do not plan to open-source the project, too many features is not always good. I like simplicity

**Comment by invisiblek** [comment]
That's pretty unfortunate for what's really the best start to a native Android app. This thing could definitely stand to have some community involvement and polishing done. Not sure your motives for keeping it closed, but it seems like a hurdle for for improvement.

**Comment by Patrik-svobodik** [comment]
I see that you want money, it’s fine for me, but I would still apprecciate it beiing opensource, and I am not alone. Just implement an system for buying the product and restoration of purchase for older customers and then you would be able to make it opensource w/out losing the money.
