### ISSUE TITLE
Non standard ports

### ISSUE THREAD

**Issue by pelted** [2ndalpha/octoremote#17]
Is octoremote bound to port 80? I can not get it connecting to anything but 80 or 443. Is there a reason for this or just a bug?

**Comment by 2ndalpha** [comment]
It also works on other ports, I'm using port 7000

**Comment by pelted** [comment]
Umm, odd. I've tried a couple of different ones and only seems to work with no port in the server url.

**Comment by 2ndalpha** [comment]
What's your setup. What's in front of OctoPrint for port forwarding?

**Comment by gitterdoneplease** [comment]
I'm using pfsense to port NAT 443 back into my LAN. Outside port is not 443. I cannot enter the server as IP:port. What is the proper format or are non-standard ports not supported?

**Comment by 2ndalpha** [comment]
Why you can't enter the address as IP:port?
Does it give an error? I'm successfully running it on port 9000
