### ISSUE TITLE
System menu

### ISSUE THREAD

**Issue by mrp192** [2ndalpha/octoremote#21]
I updated lastnight. I went to turn on my printer this morning with the app and it doesn't turn on my printer. I can still do it on the browser just not this app.

**Comment by 2ndalpha** [comment]
Can you share any more details please.
Does it give an error message? Does it crash? Do other functions work or you can't use any of its functions?

**Comment by mrp192** [comment]
It does not crash. No errors. I can restart octopr No problem in app.

**Comment by 2ndalpha** [comment]
Sorry for slow response. Could you please tell me the name of the folder you are trying to access.
And please try once more. I should receive the error log from Fabric.

**Comment by mrp192** [comment]
It's not a folder problem. All the files are in alphabetical order and it would be nice to have the option to change that to upload date. 

I'll try to record what is happening when I try to turn on my printer from the app.

**Comment by 2ndalpha** [comment]
I will close the issue, if it still happens please reopen the issue
