### ISSUE TITLE
Apple Watch app keeps saying "Printer not configured"

### ISSUE THREAD

**Issue by mxvilla** [2ndalpha/octoremote#25]
I purchased the app and configured my Octopi-connected printer on the iPhone...but the Watch app keeps saying "Printer not configured".

Is there a fix for that?

Thanks

**Comment by 2ndalpha** [comment]
Hi @mxvilla, I'm sorry you are having issues with the app.
Could you please try again. Uninstall the app, install both apps (iPhone, watch), open both and configure it in the iPhone.
Let me know if it works or not. Apple SDK for communicating between watch and the phone is not that reliable, sometimes it just fails to work.

**Comment by mxvilla** [comment]
Hi!

After a couple of tries, it's now working. I hope it stays this way!
Thanks for your reply, I'll let you know if it fails again :)



[image: --]
Maximiliano Villa
[image: http://]about.me/mxvilla
<http://about.me/mxvilla?promo=email_sig>

**Comment by 2ndalpha** [comment]
I'm glad you got it working :)
Now it should work without hiccups, it needs to fetch the server details only on the first launch. If the location of your OctoPrint server changes then it needs to synchronise again.
