### ISSUE TITLE
Flip webcam picture

### ISSUE THREAD

**Issue by CatSailer1279** [2ndalpha/octoremote#4]
Hi,
just bought your app some days ago. Nice App!
I flipped my webcam picture in the octoprint settings in both directions. But in the app picture won´t be flipped. Would be nice if you can add this feature.

**Comment by 2ndalpha** [comment]
Thanks for reporting it.
It was implemented but when I rewrote code for fetching images, I forgot to re-add it.
It will be in the next release (1.20).

**Comment by CatSailer1279** [comment]
Thanks. :)
