### ISSUE TITLE
Confirmation of cancel

### ISSUE THREAD

**Issue by MusedLife** [2ndalpha/octoremote#7]
Confirmation  button is needed for cancelling. The cancel button is huge and easy to hit accidentally. I lost an eight hour print when I changed apps. 

Please, please add a confirmation. I want to change my review from one star to five and sing your praises. There is at least one additional reviewer asking for this fix. 

Thank you.

**Comment by 2ndalpha** [comment]
Sorry for your lost print.
I read every single review and I'm aware of the issue. I just didn't have time to implement it.
It will be in version 1.26, I submitted it to Apple, it will take day or two to be released.
![simulator screen shot 19 nov 2016 16 43 53](https://cloud.githubusercontent.com/assets/2319203/20462569/003d552e-af2a-11e6-826a-db46e9fca078.png)

**Comment by MusedLife** [comment]
Thank you. I'll be happy to start using your app again.
