### ISSUE TITLE
Can't open GCode files in Folder

### ISSUE THREAD

**Issue by marcedi** [2ndalpha/octoremote#9]
I created a folder in OctoPrint for some GCodes I often need. When using the App, it is not possible to enter the folder the choose these files inside the folder.

**Comment by 2ndalpha** [comment]
Creating folders is new feature introduced in latest OctoPrint: https://github.com/foosel/OctoPrint/releases/tag/1.3.0rc1
I haven't implemented support for folders to Octo Remote. I will look into it in coming days.

**Comment by marcedi** [comment]
Thanks for your quick reply and for having a look on it.

**Comment by 2ndalpha** [comment]
Folder support has been added to the latest version in the App Store (v1.29)

**Comment by marcedi** [comment]
Works perfect ! Thank you very much. Only for future releases: marking the folder with a symbol and deleting the filesize inside the folder will be more usable.

Have a nice Christmas time.
